name: Deploy Github Pages
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install node_modules
      run: yarn
    - name: Install config env file
      run: yarn install:config
      env:
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_SENDER_ID: ${{ secrets.FIREBASE_SENDER_ID }}
        FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        MAIL_API_KEY: ${{ secrets.MAIL_API_KEY }}
    - name: Run deploy script
      run: yarn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}