name: Deploy Github Pages
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install node_modules
      run: yarn
    - name: Run deploy script
      run: yarn deploy